### PR TITLE
fix Typescript errors

### LINKED ISSUE #14: 4.1.2 Fails on yarn build in typescript
I've included this package in my project and when I try to build it I get the following error:
```
node_modules/node-libxml/index.d.ts:172:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

export = Libxml;
```
I've reverted to 4.1.1 which doesn't have declaration files and that works fine.

### PR DESCRIPTION
**Pull request by polomsky**
Fixes #14.
At least works with TS 4.7.3

### CODE REVIEW

**Comment by MatthD** [comment]
All of this is fixed in V5  thanks!

**Comment by polomsky** [comment]
Thank you @MatthD, but your version V5 is still not usable to me, because of 
```
d:\temp\test>node index.js
d:\temp\test\node_modules\node-libxml\index.ts:2
import binding from "node-gyp-build";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (d:\temp\test/\index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Node.js v18.12.1
```

The content of index.js is only `require('node-libxml')`
